"""add scan history and user scan_count

Revision ID: 8d8e9a6b7ba6
Revises: 0127d7302a21
Create Date: 2025-09-27 15:20:52.060515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8e9a6b7ba6'
down_revision = '0127d7302a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('weed_name', sa.String(length=120), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('scan_count_at_scan', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_history_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_history_weed_name'), ['weed_name'], unique=False)

    # Add scan_count with a server_default so existing rows satisfy NOT NULL
    # Note: server_default is a string at the DDL level for most backends.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scan_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('scan_count')

    with op.batch_alter_table('scan_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_history_weed_name'))
        batch_op.drop_index(batch_op.f('ix_scan_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_scan_history_detected_at'))

    op.drop_table('scan_history')
    # ### end Alembic commands ###
